services:
  tritonserver-lru-wrapper:
    image: tritonserver-lru-wrapper
    container_name: tritonserver-lru-wrapper
    network_mode: host
    environment:
      APP_MODE: "PRODUCTION"
      TRITON_HTTP_URL: "http://localhost:7000"
  
